### ISSUE TITLE
License missing from repo

### ISSUE THREAD

**Issue by karan** [GoLangPhilly/golangphilly.github.io#9]
Without a license, this project isn't open source and no one can use the code.

Please use something like http://choosealicense.com/ to decide what license to use. I recommend MIT or GPL.

**Comment by dherbst** [comment]
This is a website, not code.  Neither mit nor gpl fit well.  Perhaps Creative Commons for the original writing in the website (of which there is very little), but as it is stands it is copyright by the contributors to GoLangPhilly as you point out.

@djworth I propose Creative Commons v4.  
This work is licensed under a Creative Commons Attribution 4.0 International License.   That line with a link to http://creativecommons.org/licenses/by/4.0/ should suffice.

PR coming.

**Comment by dherbst** [comment]
Website changed to CC.
